export const UserData = {
   name:'Elon Musk',
   userName:'@elonmusk',
   userImage:"x logo.png"
}

export const PostData = [
  
   {  
      id: 1,
      name: 'Anonymous_32',
      username: '@anonymous358496',
      userImage: "2.jpg",
      postMessage: "Strength and resilience in every step. Let's support access to clean water for all. 💧 #WaterIsLife #CommunityStrong",
      postImage: "p9.jpeg",
      postVideo: 'NULL',
      time: "1h",
      reply: "4k",
      repost: "2k",
      like: "125k",
      views: "536K",
      bio: "We are Anonymous, we are legion, we do not forgive, we do not forget. Expect us.",
      followers: "20k",
      following: "50",
      follow: "True"
   },
   {
      id: 2,
      name: 'Alexander Smith',
      username: '@alexsmith',
      userImage: "5.jpg",
      postMessage: 'Guess Who?',
      postImage: "p1.jpeg",
      postVideo: 'NULL',
      time: "11h",
      reply: "4k",
      repost: "2k",
      like: "125k",
      views: "536K",
      bio: "Music lover and aspiring artist. Sharing my journey and creativity! 🎶✨",
      followers: "15k",
      following: "30",
      follow: "False"
   },
   {
      id: 3,
      name: 'Jeff',
      username: '@jeff',
      userImage: "10.jpg",
      postMessage: 'Simply Soothing!',
      postImage: "NULL",
      postVideo: "p2.mp4",
      time: "10h",
      reply: "4k",
      repost: "2k",
      like: "125k",
      views: "536K",
      bio: "Nature enthusiast capturing beautiful moments. Let's explore together! 🌲📸",
      followers: "25k",
      following: "80",
      follow: "False"
   },
   {
      id: 4,
      name: 'Mike',
      username: '@mike325',
      userImage: "4.jpg",
      postMessage: 'New Version Ready, Testing It Out!',
      postImage: "NULL",
      postVideo: "p4.mp4",
      time: "9h",
      reply: "4k",
      repost: "2k",
      like: "125k",
      views: "536K",
      bio: "Software developer with a passion for innovation. Building the future, one line at a time! 💡🔧",
      followers: "12k",
      following: "60"
   },
   {
      id: 5,
      name: 'Christine',
      username: '@christy32',
      userImage: "1.jpg",
      postMessage: 'Epic moments from the live concert performance!',
      postImage: "NULL",
      postVideo: "p5.mp4",
      time: "8h",
      reply: "4k",
      repost: "2k",
      like: "125k",
      views: "536K",
      bio: "Concert junkie and music lover. Capturing the magic of live performances! 🎶✨",
      followers: "30k",
      following: "100",
      follow: "True"
   },
   {
      id: 6,
      name: 'Elon Musk',
      username: '@elonmusk',
      userImage: "x logo.png",
      postMessage: 'Today at 3:00 PM in Los Angeles, California. Launched Successfully! 🛰️',
      postImage: "p3.jpg",
      postVideo: 'NULL',
      time: "0h",
      reply: "4k",
      repost: "2k",
      like: "125k",
      views: "536K",
      bio: "Tech entrepreneur and engineer. CEO of SpaceX and Tesla. Innovating for a better future! 🌍💡",
      followers: "155M",
      following: "110"
   },
   {
      id: 7,
      name: 'Vincent',
      username: '@vincent568',
      userImage: "7.jpg",
      postMessage: 'Enjoyed a lot!!',
      postImage: "p6.jpeg",
      postVideo: "NULL",
      time: "17h",
      reply: "4k",
      repost: "2k",
      like: "125k",
      views: "536K",
      bio: "Artist and creator. Expressing my thoughts through art. Join me on my journey! 🎨🌈",
      followers: "8k",
      following: "20",
      follow: "False"
   },
   {
      id: 8,
      name: 'Steve Drake 💪',
      username: '@steve',
      userImage: "8.jpg",
      postMessage: "Powering up for a workout! #fitness #gym #healthyhabits",
      postImage: "p7.jpeg",
      postVideo: "NULL",
      time: "16h",
      reply: "4k",
      repost: "2k",
      like: "125k",
      views: "536K",
      bio: "Fitness enthusiast dedicated to a healthy lifestyle. Let's get stronger together! 🏋️‍♂️🥗",
      followers: "50k",
      following: "200"
   },
   {
      id: 9,
      name: 'George Thomas',
      username: '@thomas',
      userImage: "9.jpg",
      postMessage: "Celebrating life with vibrant colors and joyful moments! #LookMyDab #FestivalVibes #CommunityGathering 🎉🌈",
      postImage: "p8.jpeg",
      postVideo: "NULL",
      time: "5h",
      reply: "4k",
      repost: "2k",
      like: "125k",
      views: "536K",
      bio: "Lover of festivals and community events. Spreading joy and positivity! 🎊💖",
      followers: "18k",
      following: "70"
   },
   {
      id: 10,
      name: 'Bill Payne 🦋',
      username: '@bill',
      userImage: "4.jpg",
      postMessage: 'An Adventurous & Scary Dream last night!',
      postImage: "p10.jpeg",
      postVideo: "NULL",
      time: "4h",
      reply: "4k",
      repost: "2k",
      like: "125k",
      views: "536K",
      bio: "Dreamer and storyteller. Sharing my thoughts and experiences! 🌌📖",
      followers: "10k",
      following: "25"
   },
    {
      id: 11,
      name: 'Elon Musk',
      username: '@elonmusk',
      userImage: "x logo.png",
      postMessage: 'To the Mars!!',
      postImage: "p14.jpeg",
      postVideo: "NULL",
      time: "21h",
      reply: "4k",
      repost: "2k",
      like: "125k",
      views: "536K",
      bio: "Tech entrepreneur and engineer. CEO of SpaceX and Tesla. Innovating for a better future! 🌍💡",
      followers: "155M",
      following: "110"
   },
   {
      id: 12,
      name: 'Yodha Team',
      username: '@yodha',
      userImage: "6.jpg",
      postMessage: "The coolest pup in town! 😎🐾 #dogsofinstagram #fashionista #adorablepets",
      postImage: "NULL",
      postVideo: "p11.mp4",
      time: "2h",
      reply: "4k",
      repost: "2k",
      like: "125k",
      views: "536K",
      bio: "A fun-loving dog with a flair for fashion! 🐶👗",
      followers: "5k",
      following: "10",
      follow: "True"
   },
   {
      id: 13,
      name: 'Rick Astley',
      username: '@rickastley',
      userImage: "7.jpg",
      postMessage: "Cute and curious, penguins are always a delightful sight to watch! #penguins #australia #wildlife",
      postImage: "NULL",
      postVideo: "p12.mp4",
      time: "1h",
      reply: "4k",
      repost: "2k",
      like: "125k",
      views: "536K",
      bio: "Singer and wildlife lover. Sharing my passion for music and nature! 🌊🎶",
      followers: "1M",
      following: "150"
   },
   {
      id: 14,
      name: 'Quincy',
      username: '@quincy',
      userImage: "3.jpg",
      postMessage: "Above the clouds, chasing adventures! ✈️☁️ #windowseatviews",
      postImage: "p13.jpg",
      postVideo: "NULL",
      time: "3h",
      reply: "400",
      repost: "23",
      like: "2k",
      views: "15K",
      bio: "Travel enthusiast capturing moments from around the world. 🌎📷",
      followers: "9k",
      following: "30"
   }
]
 